# Generated by Django 5.0 on 2024-01-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('cover_picture', models.ImageField(upload_to='category/')),
            ],
            options={
                'db_table': 'category_tb',
            },
        ),
        migrations.CreateModel(
            name='EkartAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('passsword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_tb',
            },
        ),
    ]
